import type { Metadata } from "next";
import  "bootstrap/dist/css/bootstrap.min.css"
import './ui/globals.css';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-vh-100 d-flex justify-content-center align-items-start">
          {children}
      </body>
    </html>
  );
}
